### ISSUE TITLE
Having trouble adapting your `qt6ct` override

### ISSUE THREAD

**Issue by spikespaz** [ilya-fedin/nur-repository#19]
Generally, I'm a pretty experienced Nix user. However, this has me stumped. Maybe you could update your flake's `nixpkgs` input and try to build the package ***from the overlay***?

Here, I have changed a few things. First, you have a top-level `with`. This is discouraged for what should be obvious reasons (shadowing/clashes, identifier originator ambiguity, thunking). Secondly, I am using [Home Manager's `qt` module](https://github.com/nix-community/home-manager/blob/master/modules/misc/qt.nix) which appears to be more correctly configured than the one I had made. The reason the package below overrides the name `pkgs.qt6Packages.qt6ct` is that the aforementioned module is hard-coded to use that attribute path. 

```nix
pkgs: pkgs0:
let inherit (pkgs) lib;
in {
  # Does someone know the difference between `kdePackages` and `qt6Packages`?
  # I have tried to find where `kdePackages` is defined and all I can find
  # (that isn't direct usage) is a scope splice.
  # It seems that `qt6Packages` is the earliest instantiation of all the
  # derivations within, and that `kdePackages` probably inherits from it
  # (the scope splice I mentioned).
  # But, `qt6Packages` is not listed in the (unstable) package search
  # (it is in stable).
  # Some Home Manager modules are hard-coded to use `qt6Packages`,
  # but that namespace is (now) missing on the Package Search webpage.
  qt6Packages = pkgs0.qt6Packages // {
    qt6ct = pkgs0.qt6Packages.qt6ct.overrideAttrs (self: super: {
      patches = super.patches or [ ] ++ [
        (pkgs.fetchpatch {
          url =
            "https://patch-diff.githubusercontent.com/raw/trialuser02/qt6ct/pull/43.diff";
          hash = "sha256-r7KtusyM7MWYN/RXpc/CJf3IOLkuN5+FJpa4dNa9b7M=";
        })
      ];
      buildInputs = super.buildInputs or [ ] ++ (with pkgs.kdePackages; [
        qtdeclarative
        kconfig
        kcolorscheme
        kiconthemes
      ]);
      nativeBuildInputs = super.nativeBuildInputs or [ ]
        ++ (with pkgs; with pkgs.kdePackages; [ cmake wrapQtAppsHook qttools ]);
      cmakeFlags = [
        "-DPLUGINDIR=${
          placeholder "out"
        }/${pkgs.kdePackages.qtbase.qtPluginPrefix}"
      ];
    });
  };
}
```

If you're wondering if the nested attributes override / scope re-splicing works, yes, it does (for everything else at least). I'm just not sure if `kdePackages` usage is causing the problem here.

```
       > qt6ctplatformtheme.cpp:47:10: fatal error: QQuickStyle: No such file or directory
       >    47 | #include <QQuickStyle>
       >       |          ^~~~~~~~~~~~~
```

**Comment by ilya-fedin** [comment]
kdePackages was introduced with Plasma 6. Is your system out-of-date? 🤔

You can't use the patch without Plasma 6 packages, obviously.

**Comment by spikespaz** [comment]
No, it isn't out of date. Both namespaces exist, only `kdePackages` is shown on the website. `kdePackages` is larger (obviously) than `qt6Packages`, and IMO, `qt6Packages` should remain right where it is. Qt is an entirely separate product from KDE Plasma 6. There is no deprecation notice. As you can see, I successfully use derivations from `kdePackages` (and HM uses them from `qt6Packages`). If they weren't successfully found, the error I pasted would not show, rather, I would see an error pertaining to missing attributes.

**Comment by ilya-fedin** [comment]
Indeed, the overlay seem to be leading for infinite recursion which I don't really understand how happens.

In case of your overlay, I see two problems:
1. It concatenates nativeBuildInputs with old ones rather than replacing them so it continues to use qmake which is not supported by KDE Frameworks (as far as I'm aware)
2. The patch in this repo differs including a nix-specific fix to let nix build with cmake correctly.

It's also meant to be used with the module as the entrypoint, as it won't work correctly without qqc2-desktop-style in session QT_PLUGIN_PATH.

**Comment by ilya-fedin** [comment]
Oh, looks like I managed to fix it

**Comment by spikespaz** [comment]
Yeah, I was about to say, you wouldn't see the error I do if it had infinite recursion.

**Comment by ilya-fedin** [comment]
well, now it builds for me just fine

**Comment by spikespaz** [comment]
So what happened to `qtbase qtsvg qtwayland`? Does `qttools` take care of them or something?

---

> The patch in this repo differs including a nix-specific fix to let nix build with cmake correctly.

I assume the problem is this then:

```
       > CMake Error at src/qt6ct-qtplugin/cmake_install.cmake:60 (file):
       >   file INSTALL cannot copy file
       >   "/build/source/build/src/qt6ct-qtplugin/libqt6ct.so" to
       >   "/nix/store/2mcqdmp7kb8pfkibxsm10z3s94j80s6y-qtbase-6.6.3/lib/qt-6/plugins/platformthemes/libqt6ct.so":
       >   Permission denied.
       > Call Stack (most recent call first):
       >   cmake_install.cmake:57 (include)
       >
```

Well, what is the objective for upstream? If that patch ever (were to) get merged, we would need another to fix this. Is there a CMake flag that can change the install prefix for that library? So that we don't need the second patch?

**Comment by ilya-fedin** [comment]
> we would need another to fix this

Yeah, it's quite orthogonal to the KDE changes and could be a separate PR if the KDE one will ever get merged.

> Is there a CMake flag that can change the install prefix for that library?

No, qt6ct always uses an utility from qttools to get the plugin directory. I change it to get the path only if PLUGINDIR is not already specified.

**Comment by spikespaz** [comment]
And the first question about the removed `nativeBuildInputs`?

---

Would you mind making that separate patch and making a PR to upstream, with a note that [#43](https://github.com/trialuser02/qt6ct/pull/43) is prerequisite?

**Comment by spikespaz** [comment]
The reason I ask is I would like to see this in Nixpkgs, under a different name (with `-kde` as a suffix, like Arch) and fix the HM module so that it doesn't use a hard-coded attribute.

**Comment by ilya-fedin** [comment]
> with a note that [#43](https://github.com/trialuser02/qt6ct/pull/43) is prerequisite?

Why? It's not a prerequisite at all, as I said, it's an orthogonal nix-specific problem. It exists since qt5ct times and apparently the reason nixpkgs uses qmake rather than cmake.

**Comment by spikespaz** [comment]
Then never mind the "prerequisite" part. Mind making the patch separate?

Also, still curious what happened to `qtbase qtsvg qtwayland` in the original `nativeBuildInputs`. Why are they not necessary?

**Comment by ilya-fedin** [comment]
> Mind making the patch separate?

Here you go: https://github.com/trialuser02/qt6ct/pull/44

> Also, still curious what happened to `qtbase qtsvg qtwayland` in the original `nativeBuildInputs`.

They are in buildInputs, not nativeBuildInputs...

**Comment by spikespaz** [comment]
1. Thank you.
2. RIP

**Comment by ilya-fedin** [comment]
Can I close the issue?

**Comment by spikespaz** [comment]
Yes

**Comment by spikespaz** [comment]
Thank you for the help BTW, I really appreciate it.
